### ISSUE TITLE
psc 0.11.x compatibility

### ISSUE THREAD

**Issue by owickstrom** [purescript-node/purescript-node-http#13]
I can send a PR, if that's OK?

**Comment by paf31** [comment]
That'd be great, although there are some dependencies which need to be updated first.

**Comment by owickstrom** [comment]
yeah, I noticed once I started digging in. :)

**Comment by nick-brady** [comment]
https://github.com/purescript-node/purescript-node-http/commit/6fc844d6aa22eb695403042923cd3c0c74203828 closes this right?

**Comment by paf31** [comment]
Yes, thanks.
