### ISSUE TITLE
Won't install with yarn

### ISSUE THREAD

**Issue by ecausarano** [purescript-node/purescript-node-http#20]
Hi, using yarn I get
```
$ yarn add purescript-node-http                                   
...
error Couldn't find package "purescript-node-http" on the "npm" registry.
```
ok, let's use the git form:
```
yarn add https://github.com/purescript-node/purescript-node-http
...
error Package "undefined@undefined" doesn't have a "name".
```
guess there's something missing in the yarn descriptor?

**Comment by hdgarrood** [comment]
I don't know what a yarn descriptor is, but this package is not intended to be installed with either npm or yarn, and hence it is not on the npm registry, which is why this isn't working. Try bower or psc-package instead.

**Comment by ecausarano** [comment]
Hi, please consider reopening... bower has been deprecated in favor of yarn. See https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by hdgarrood** [comment]
Sorry, this isn't going to happen. We're aware that bower has been deprecated, and people are working on alternatives e.g. psc-package, but the way npm handles dependency conflicts is not appropriate for purescript.

**Comment by ecausarano** [comment]
Uh, sorry? I'm just suggesting you add a name (version, license, author, whatever you feel) fields to the package.json so yarn won't croak when I add the module straight from the git repo (without using npm) as in 
```
yarn add https://github.com/ecausarano/purescript-node-http\#bugfix/wont-install-yarn-20
```
You can still keep it private=true, just add the other fields and yarn is happy...

**Comment by garyb** [comment]
Bower support was removed from Yarn: https://github.com/yarnpkg/yarn/pull/1441
