### ISSUE TITLE
Add support for `connection`

### ISSUE THREAD

**Issue by joneshf** [purescript-node/purescript-node-http#25]
The node.js `http` module has had support for `request.connection` for ages (since version 0.3.0), it's just been poorly documented. Up until the 8.x series it was tucked away in the comment of the [`'connection'` event][event]. Since then, it's had [its own documentation][connection]. I'd like to propose we add support for `connection`, but it will require some work for the [`Socket`][socket] it returns.

My guess (and what I mentioned on slack) is that we'll want a `purescript-node/purescript-node-net` package, where we have `Socket` and all its facilities defined. If that's the case, I'm more than happy to do the work if someone can make the repo. Then, we can expose `connection :: Node.HTTP.Request -> Node.Net.Socket`. Does that sound about right?

[connection]: https://nodejs.org/docs/latest-v8.x/api/http.html#http_request_connection
[event]: https://nodejs.org/docs/latest-v0.10.x/api/http.html#http_event_connection
[socket]: https://nodejs.org/docs/latest-v8.x/api/net.html#net_class_net_socket

**Comment by hdgarrood** [comment]
Sounds good to me. I guess we don’t yet have bindings for net.Server either?

**Comment by hdgarrood** [comment]
@joneshf here you go: https://github.com/purescript-node/purescript-node-net

**Comment by joneshf** [comment]
Thanks!

**Comment by garyb** [comment]
I invited you to be an admin of the org a while back actually, did that ever come through?

**Comment by joneshf** [comment]
Yeah, I accepted that as well (I'm just slow :blush:). Thanks!

**Comment by JordanMartinez** [comment]
Fixed by #49.
