### ISSUE TITLE
Add support  for http2

### ISSUE THREAD

**Issue by squidCatx** [purescript-node/purescript-node-http#44]
HTTP/2 is Stable in nodejs v10.10.0

**Comment by jamesdbrock** [comment]
I want this too. For https://github.com/xc-jp/purescript-protobuf/issues/34

**Comment by jamesdbrock** [comment]
Would http/2 be added to this repo, or would it be a separate repo?

**Comment by JordanMartinez** [comment]
I think keeping it in this repo would make updating the ecosystem that much easier since there's one less library to fix. I'd also imagine that some things are shareable between the two, but I'm not familiar with this area.

**Comment by jamesdbrock** [comment]
So would you be interested in a PR for a new module `Node.HTTP2` in this repo?

**Comment by JordanMartinez** [comment]
Sure.

**Comment by jamesdbrock** [comment]
Do we want to add a `spago.dhall` to this repo?

**Comment by JordanMartinez** [comment]
I'd prefer we don't add a `spago.dhall` here. It makes doing breaking changes easier.

**Comment by jamesdbrock** [comment]
Can we add an Aff dependency to this repo for `Aff` modules?

The main constraint for Aff is that it only works on JavaScript backends. But Node.js also only works on JavaScript backends, so no new constraint will be introduced.

**Comment by JordanMartinez** [comment]
I think that's fine.

**Comment by jamesdbrock** [comment]
> I think that's fine.

Great. Then I would also like to donate https://pursuit.purescript.org/packages/purescript-node-streams-aff/2.0.0 to __purescript-node__ org and become a member of __purescript-node__ org. Is that cool @JordanMartinez ?

**Comment by JordanMartinez** [comment]
I'm fine with you becoming a member. Let me check with others first.

**Comment by jamesdbrock** [comment]
I'm working on HTTP/2. I have a branch here which passes basic client/server tests for HTTP/2 and also includes an `Aff` API. https://github.com/jamesdbrock/purescript-node-http/tree/http2

**Comment by JordanMartinez** [comment]
> > I think that's fine.
> 
> Great. Then I would also like to donate https://pursuit.purescript.org/packages/purescript-node-streams-aff/2.0.0 to **purescript-node** org and become a member of **purescript-node** org. Is that cool @JordanMartinez ?

I've sent you an invite.

**Comment by jamesdbrock** [comment]
https://github.com/JordanMartinez/purescript-node-http2

https://discourse.purescript.org/t/rfc-eventemitter-bindings-and-http2-bindings/3584

**Comment by jamesdbrock** [comment]
Excerpt from the docs for this PR. This is what the API basically looks like.

## Server-side example

Equivalent to [Node.js HTTP/2 Core API Server-side example](https://nodejs.org/docs/latest/api/http2.html#server-side-example)

```purescript
import Node.Stream.Aff (write, end)

key <- Node.FS.Sync.readFile "localhost-privkey.pem"
cert <- Node.FS.Sync.readFile "localhost-cert.pem"

either (liftEffect <<< Console.errorShow) pure =<< attempt do
  server <- createSecureServer (toOptions {key, cert})
  listenSecure server (toOptions {port:8443})
    \session headers stream -> do
      respond stream
        (toOptions {})
        (toHeaders
          { "content-type": "text/html; charset=utf-8"
          , ":status": 200
          }
        )
      write (toDuplex stream) =<< fromStringUTF8 ("<h1>Hello World<hl>")
      end (toDuplex stream)
```

## Client-side example

Equivalent to [Node.js HTTP/2 Core API Client-side example](https://nodejs.org/docs/latest/api/http2.html#client-side-example)

```purescript
import Node.Stream.Aff (readAll)

ca <- liftEffect $ Node.FS.Sync.readFile "localhost-cert.pem"

either (liftEffect <<< Console.errorShow) pure =<< attempt do
  client <- connect
    (toOptions {ca})
    (URL.parse "https://localhost:8443")

  stream <- request client
    (toOptions {})
    (toHeaders {":path": "/"})

  headers <- waitResponse stream
  liftEffect $ for_ (headerKeys headers) \name ->
    Console.log $
      name <> ": " <> fromMaybe "" (headerString headers name)

  body <- toStringUTF8 =<< (fst <$> readAll (toDuplex stream))
  liftEffect $ Console.log $ "\n" <> body

  closeSession client
```
